# HelmRelease values patch containing secrets (to be encrypted with SOPS)
# Encrypt with: sops --encrypt --in-place offer-renderer.release.secret.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: offer-renderer
    namespace: offer-renderer
spec:
    values:
        secrets:
            data:
                DATABASE_URL: ENC[AES256_GCM,data:hIbB1CkUo0nRzV9mnMOGmY7ryIB6b0J/inBAJaOTmHtz6FwTh9WKc5Nq8YcTsJjxwDV0Z8SwBXfPQ+0aKNsYYBrp9C+GqRHfYqV6eP+17X9gznjpyjxmL5SNPY1skDRXDEI+Z4y+TMIJ9KEVqk6/DTaRrlptFt88qaWo2rLLeSdAG9/dt7U/xo+UOXZ7wcfugVNxKvRcdtQq,iv:gWxA/i6ffr9WKae7Ym3qpS+QfJtiy7F7UUepPPi7BIQ=,tag:h9Vg6yfwmYnupK0yd7kWVA==,type:str]
                API_KEY: ""
                SENTRY_DSN: ""
sops:
    gcp_kms:
        - resource_id: projects/popshop-staging/locations/us-west1/keyRings/vault-unseal-kr/cryptoKeys/kotlin-backend-flux-sops-key
          created_at: "2026-03-06T14:46:25Z"
          enc: CiYAg4f6nTAGE65ab9Vt85PuNJ7r84+I6O5rHpYGtdTKsGQB/D+yXhJJAN7GSfzQiDKuSNURxJ2hued/o+uafnO11HAk8nLAdVTQdEHkGwakq9z9qOHLI1RktGoLaEKCC62FkjRuc0jCdhqMK2+MCDVzCQ==
        - resource_id: projects/popshop-staging/locations/us-west1/keyRings/vault-unseal-kr/cryptoKeys/frontend-flux-sops-key
          created_at: "2026-03-06T14:46:25Z"
          enc: CiYAsW3djPLlJbyd/WKlyhknE/lCFhBw9Z2XBSHDjjdaI5pzp3QwrBJJAMr5OTGOw71sZCpzMC0TlFXokVOVMVfAzsW0WIY1q/rmAxe2DWuwPuO8xVtp/lKlsf6R5mhNTAJnSErnVKnh7Iry3o6SJKmaHg==
    lastmodified: "2026-03-06T14:46:28Z"
    mac: ENC[AES256_GCM,data:Phq3G7hIunti+VuLe8TJAQzz82G3l16NmIuD2jy9SN9+he5quwxvGlmx70hzx8H9VOhCBYqLCK/Y3OVf9mPzZvPS2dIsr2eLh5Fcjs9jT6BDBTsi682F4id10WgU9PSMB2oadXIzwR1vYfUdNMN5Wm+eV907DcbzA6qHirZ9+cM=,iv:68xO2Xte2zXYqj+D4pLYLkXHPFh6LWJE+bIKPP0drr0=,tag:03LfaUfsxPsJLEljhtOQSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
