# HelmRelease values patch containing secrets (to be encrypted with SOPS)
# Encrypt with: sops --encrypt --in-place offer-renderer.release.secret.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: offer-renderer
    namespace: offer-renderer
spec:
    values:
        secrets:
            data:
                DATABASE_URL: ENC[AES256_GCM,data:Sn8asXcEMVbqn2mqJpnBq4cvtyF5OcUhGGL63z2ZdIeleTp17WSHvxbWXNnqMSLmYFBVbwSGE/bT/nVaS8BjaseIWb5YYymabHSFkcr5tuSllQ8q2YCVY8FKxDGlknnmLViinVTcI5XinSkyOd4NW6zbQMORrah/cupt5lOOScXt2BD0DYr93CDv6sbc9/HGU8MCEhuUiIZr,iv:X/saeGTZY+JEJR4Z8n7ekO+lJVBWI7zXho1WPLi/AnA=,tag:RONBnCLRyDZ5YrOuy6Trqw==,type:str]
                API_KEY: ""
                SENTRY_DSN: ""
sops:
    gcp_kms:
        - resource_id: projects/popshopprod/locations/us-west1/keyRings/vault-unseal-kr/cryptoKeys/kotlin-backend-flux-sops-key
          created_at: "2026-03-06T14:46:28Z"
          enc: CiYAzxf6jR1Hvbj8DgbzM/U07R+kS6nixq6z6akik05EpRzU1DM9ARJJAO/cDTkxBc4Ot+WLCrNIqOBC5tY8vIjUKJPtKPnBBKXwrHei2Jzr5VEvSQLKQ/l9popyAYpF1jfQdU9EjEsVVi4ruYCgANQ4IA==
        - resource_id: projects/popshopprod/locations/us-west1/keyRings/vault-unseal-kr/cryptoKeys/frontend-flux-sops-key
          created_at: "2026-03-06T14:46:28Z"
          enc: CiYAqEgzj4iEMerwY9KGV96uvExqcN08EY0eMouEJotIffxa9ijbhxJJAOLJAFI4jMlhPAHxAdgHGbAm9I3ZYey9so9VNB10CTyQKprzjJXDKJc98+VmKsRkGpQi/8vlc3iH5DDtkmtqjkUxUANY1bf0xg==
    lastmodified: "2026-03-06T14:46:30Z"
    mac: ENC[AES256_GCM,data:+U9GDEhy9+cfxSCSlYqwbdahBqWP/vmLgQ8P8ytddMswHtSF59ECREHIOTfdvPKRXjYVerUlAEJTEOm/YaN+23vAr5ICpeig7CplOAiDEHTW1sU9AbKFHtZ4JSh7aDNjvalK7bFnECdibz5O0mmFm0gZkV9L8/1N2YzKuwT7m6E=,iv:rWKc4VCAuLE1SpOPRzeJaIgx5+eTPkS8E6zEnE62YWg=,tag:HqWVK+mZAxTPUpYydHnUFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
